#!/usr/bin/env node

//  ---------------------------------------------------------------------------------------------------------------  //

var path_ = require('path');

//  ---------------------------------------------------------------------------------------------------------------  //

var nopt = require('nopt');

var options = nopt({
    'port': String,
    'socket': String,
    'rootdir': String,
    'config': String,
    'help': Boolean
});

if (options.help) {
    usage();
}

//  ---------------------------------------------------------------------------------------------------------------  //

var Descript = require('./lib/descript.js');

//  ---------------------------------------------------------------------------------------------------------------  //

var config;
if (options.config) {
    config = Descript.readConfig(options.config);
} else {
    config = {};
}

config.port = options.port || config.port;
config.socket = options.socket || config.socket;
config.rootdir = path_.resolve( options.rootdir || config.rootdir || '.' );

if ( !(config.port || config.socket) ) {
    usage();
}

function usage() {
    //  TODO.
    console.log('Usage:');
    console.log('   ./descript --port 2000 --rootdir example/pages');
    console.log('   ./descript --socket descript.sock --rootdir examples/pages');
    console.log('   ./descript --config config.json');
    console.log();

    process.exit(0);
}

//  ---------------------------------------------------------------------------------------------------------------  //

if (config.modules) {
    var dirname = path_.dirname( path_.resolve(options.config) );
    var modules = Descript.readModules(config.modules, dirname);
}

//  ---------------------------------------------------------------------------------------------------------------  //

var descript = new Descript(config, modules);

descript.start();

// vim: set filetype=javascript:

